<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="mkrishnan" ignored="0" name="ProductListPageTest" tests="8" failures="1" timestamp="21 Dec 2018 07:55:44 GMT" time="178.235" errors="0">
  <testcase name="validateProductpageExistTest" time="1.298" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateAddProductExistTest" time="1.222" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateAddProductTemplateExistTest" time="2.088" classname="com.avlview.app.testcases.ProductListPageTest">
    <skipped/>
  </testcase> <!-- validateAddProductTemplateExistTest -->
  <testcase name="validateBackButtonTest" time="1.762" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateAddProduct" time="1.68" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateSearchExistTest" time="1.287" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateDeleteProduct" time="2.399" classname="com.avlview.app.testcases.ProductListPageTest">
    <skipped/>
  </testcase> <!-- validateDeleteProduct -->
  <testcase name="validateDeleteProduct" time="1.961" classname="com.avlview.app.testcases.ProductListPageTest">
    <failure type="java.lang.AssertionError" message="expected [You just deleted a product from records.] but found [Sorry, an error occurred. The servers are unable to complete your request at the moment. Please try again after a few minutes.]">
      <![CDATA[java.lang.AssertionError: expected [You just deleted a product from records.] but found [Sorry, an error occurred. The servers are unable to complete your request at the moment. Please try again after a few minutes.]
at com.avlview.app.testcases.ProductListPageTest.validateDeleteProduct(ProductListPageTest.java:91)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateDeleteProduct -->
</testsuite> <!-- ProductListPageTest -->
